/* KaryoDraw Worker.
 *
 * Serves the static site (via the ASSETS binding) and handles three endpoints:
 * POST /api/collect records an anonymous usage event to D1, GET /api/top returns
 * the most-drawn karyotypes for the on-page "Most-studied" panel, and POST
 * /api/feedback receives a message from the on-site feedback form.
 *
 * Privacy: the usage analytics store no cookie, account, IP, user-agent, or
 * identifier — only the karyotype drawn (capped), whether it parsed, the view
 * settings, a coarse country, and the referring host. Feedback is a separate,
 * voluntary channel: it stores what the person typed, a coarse country, and, if
 * they choose to give it, an email for a reply. No user-agent, IP, or cookie is
 * stored on feedback either. Feedback is kept private and never shown.
 *
 * A daily cron (scheduled handler) emails a digest of new feedback via Resend,
 * inert until the RESEND_API_KEY / FEEDBACK_EMAIL_TO settings are configured.
 */

// Normalized ISCN notation -> landing-page slug, generated by scripts/build-pages.mjs.
// Powers the /k/<notation> shortlink redirects to the canonical /karyotype/<slug>/.
import { K_TO_SLUG } from "./content/k-index.mjs";

// Thresholds for the public "Most-studied" list. A karyotype appears once it has
// been drawn TOP_MIN_DRAWS times in total AND on at least TOP_MIN_DAYS distinct
// (not necessarily consecutive) calendar days. The total draws are the anonymity
// floor; the distinct-day rule stops one person in a single session from putting
// something on the board. Both are tunable; raise as traffic grows.
const TOP_MIN_DRAWS = 5;
const TOP_MIN_DAYS = 2;
const TOP_LIMIT = 15;

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === "/api/collect") {
      if (request.method !== "POST") return new Response("method not allowed", { status: 405 });
      // Per-IP rate limit. On limit, silently drop (204, same as success) so a
      // legitimate user is never disrupted — the analytics beacon ignores the body.
      if (await overLimit(env.RL_COLLECT, request)) return new Response(null, { status: 204 });
      // Read the body here, before returning; it is not reliably readable inside waitUntil.
      let body = null;
      try { body = await request.json(); } catch (_) { body = null; }
      const country = (request.cf && request.cf.country) || null;
      ctx.waitUntil(record(body, country, env));
      return new Response(null, { status: 204 });
    }
    if (url.pathname === "/api/top") {
      if (request.method !== "GET") return new Response("method not allowed", { status: 405 });
      return topResponse(request, env, ctx);
    }
    if (url.pathname === "/api/feedback") {
      if (request.method !== "POST") return new Response("method not allowed", { status: 405 });
      // Per-IP rate limit. Feedback is low-frequency for a real person, so a tight
      // cap stops a flood into the inbox/webhook without affecting normal use.
      if (await overLimit(env.RL_FEEDBACK, request)) return new Response("slow down", { status: 429 });
      return feedbackResponse(request, env, ctx);
    }
    // /k/<notation> is a short, notation-based link. Redirect to the canonical
    // /karyotype/<slug>/ landing page when one exists (301), otherwise open the
    // interactive tool with that karyotype (302). Keeps one canonical URL per page.
    if (url.pathname === "/k" || url.pathname.startsWith("/k/")) {
      const raw = decodeURIComponent(url.pathname.slice(3)).replace(/\/+$/, "").trim();
      if (!raw) return Response.redirect(`${url.origin}/karyotype/`, 301);
      const slug = K_TO_SLUG[raw.replace(/\s+/g, "").toLowerCase()];
      return slug
        ? Response.redirect(`${url.origin}/karyotype/${slug}/`, 301)
        : Response.redirect(`${url.origin}/?k=${encodeURIComponent(raw)}`, 302);
    }
    const res = await env.ASSETS.fetch(request);
    // Serve the branded 404 page for unknown page navigations (not missing images
    // or other assets, which should keep their plain 404). Preserves the 404 status.
    if (res.status === 404 && request.method === "GET" &&
        (request.headers.get("accept") || "").includes("text/html")) {
      const page = await env.ASSETS.fetch(new URL("/404.html", request.url));
      if (page.ok) {
        return new Response(page.body, {
          status: 404,
          headers: { "content-type": "text/html; charset=utf-8" },
        });
      }
    }
    return res;
  },

  // Scheduled (cron) handler: email a daily digest of new feedback. Registered by
  // the cron in wrangler.jsonc. Inert until the Resend settings are configured.
  async scheduled(event, env, ctx) {
    ctx.waitUntil(sendFeedbackDigest(env));
  },
};

function cap(v, n) {
  return typeof v === "string" && v ? v.slice(0, n) : null;
}

// Best-effort per-IP rate limit via a Workers Rate Limiting binding. Returns true
// when the caller should be throttled. No-ops (returns false) when the binding is
// absent — local dev, or before the binding is deployed — and never throws, since
// a limiter hiccup must not take the endpoint down. Counting is per Cloudflare
// location and approximate, which is the right trade for cheap abuse protection.
async function overLimit(limiter, request) {
  if (!limiter) return false;
  const ip = request.headers.get("cf-connecting-ip") || "unknown";
  try {
    const { success } = await limiter.limit({ key: ip });
    return !success;
  } catch (e) {
    console.error("rate limit check failed:", e && e.message);
    return false;
  }
}

// Email any not-yet-sent feedback as one digest, via Resend. Safe to deploy before
// it is configured: it no-ops unless RESEND_API_KEY and FEEDBACK_EMAIL_TO are set.
// Rows are marked digested only after the email is accepted, so a send failure
// retries on the next run instead of dropping feedback.
// Fetch up to 200 not-yet-digested rows, oldest first. Prefers the richer columns
// and falls back if the category migration has not run. Returns null on query
// failure so the caller can stop cleanly.
async function fetchUndigestedFeedback(env) {
  const tail = "WHERE digested IS NULL ORDER BY ts ASC LIMIT 200";
  try {
    return (await env.DB.prepare(
      "SELECT id, ts, message, email, karyotype, url, country, category FROM feedback " + tail
    ).all()).results || [];
  } catch (e) {
    try {
      return (await env.DB.prepare(
        "SELECT id, ts, message, email, karyotype, url, country FROM feedback " + tail
      ).all()).results || [];
    } catch (e2) {
      console.error("digest query failed:", e2 && e2.message);
      return null;
    }
  }
}

async function sendFeedbackDigest(env) {
  if (!env.RESEND_API_KEY || !env.FEEDBACK_EMAIL_TO) return;
  const from = env.FEEDBACK_EMAIL_FROM || "KaryoDraw feedback <feedback@karyodraw.com>";

  // Drain the queue in batches of 200, oldest first, so a backlog (or a spam
  // burst) cannot leave genuine feedback undigested for days. Bounded at 20
  // batches (4000 rows) per run so one invocation can never loop unbounded.
  for (let batch = 0; batch < 20; batch++) {
    const rows = await fetchUndigestedFeedback(env);
    if (!rows || !rows.length) return;

    const subject = "KaryoDraw feedback: " + rows.length + " new";
    const body = rows.map(formatFeedback).join("\n\n----------\n\n");

    let sent = false;
    try {
      const r = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { authorization: "Bearer " + env.RESEND_API_KEY, "content-type": "application/json" },
        body: JSON.stringify({ from, to: env.FEEDBACK_EMAIL_TO, subject, text: body }),
      });
      sent = r.ok;
      if (!r.ok) console.error("resend returned", r.status);
    } catch (e) {
      console.error("resend request failed:", e && e.message);
    }
    // On a send failure, stop and leave the rows undigested so the next run retries
    // them instead of dropping feedback.
    if (!sent) return;

    const ids = rows.map((x) => x.id);
    const marks = ids.map(() => "?").join(",");
    try {
      await env.DB.prepare("UPDATE feedback SET digested = 1 WHERE id IN (" + marks + ")").bind(...ids).run();
    } catch (e) {
      // If marking fails, stop rather than re-send the same rows on the next loop.
      console.error("digest mark failed:", e && e.message);
      return;
    }
    // A short (partial) batch means the queue is drained.
    if (rows.length < 200) return;
  }
}

function formatFeedback(r) {
  const when = new Date(r.ts).toISOString();
  const head = when + (r.category ? "  [" + r.category + "]" : "") + (r.country ? "  (" + r.country + ")" : "");
  const lines = [head, (r.message && r.message.trim()) ? r.message : "(flagged — no detail added)"];
  if (r.karyotype) lines.push("karyotype: " + r.karyotype);
  if (r.url) lines.push("view: " + r.url);
  if (r.email) lines.push("reply to: " + r.email);
  return lines.join("\n");
}

// POST /api/feedback — feedback and "Doesn't look right?" flags. Three shapes:
//   1. Quick flag  { quick:true, category, karyotype, url }  -> logs a row on the
//      first click and returns { id, token } so the client can enrich it.
//   2. Enrich      { id, token, category, message, email }   -> attaches optional
//      detail to that exact flag (matched by the unguessable token).
//   3. General     { message, email, karyotype, url, category } -> ordinary feedback.
// All are stored in D1 (kept private). A chat webhook, if configured, pings on
// reports that carry a message; by default it is off and the daily digest is used.
async function feedbackResponse(request, env, ctx) {
  let b = null;
  try { b = await request.json(); } catch (_) { b = null; }
  // Honeypot: a hidden field real users never fill. If it has content, drop the
  // submission silently (return OK so bots learn nothing).
  if (!b || (b.hp && String(b.hp).trim())) return new Response(null, { status: 204 });

  // (2) Enrich a previously-logged quick flag, matched by its opaque token.
  if (b.id != null && b.token) {
    const message = typeof b.message === "string" ? b.message.trim().slice(0, 4000) : "";
    const email = cap(b.email, 200);
    const category = cap(b.category, 40);
    try {
      await env.DB.prepare(
        "UPDATE feedback SET message = COALESCE(NULLIF(?, ''), message), " +
        "email = COALESCE(?, email), category = COALESCE(?, category) WHERE id = ? AND token = ?"
      ).bind(message, email, category, b.id, String(b.token)).run();
      return new Response(null, { status: 204 });
    } catch (e) {
      // Columns may not exist yet (migration not run): fall through and store the
      // detail as a fresh row so nothing is lost.
      console.error("feedback enrich failed, storing as new:", e && e.message);
    }
  }

  const quick = b.quick === true;
  const message = typeof b.message === "string" ? b.message.trim() : "";
  const category = cap(b.category, 40);
  // Ordinary feedback needs a message; a quick flag or a categorized report may
  // have none, because the click itself is the signal.
  if (!message && !quick && !category) return new Response("message required", { status: 400 });

  const ts = Date.now();
  const email = cap(b.email, 200);
  const karyotype = cap(b.karyotype, 512);
  const link = cap(b.url, 500);
  // User-agent intentionally not stored. It was only ever written, never shown in
  // the digest, so it added identifying data with no support value. The column is
  // kept for schema compatibility; new rows leave it null.
  const ua = null;
  const country = (request.cf && request.cf.country) || null;
  const token = crypto.randomUUID();

  let id = null, stored = false;
  try {
    const res = await env.DB.prepare(
      "INSERT INTO feedback (ts, message, email, karyotype, url, ua, country, category, token) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"
    ).bind(ts, message.slice(0, 4000), email, karyotype, link, ua, country, category, token).run();
    id = res.meta && res.meta.last_row_id; stored = true;
  } catch (e) {
    // Fall back to the legacy columns so feedback is never lost during the window
    // between deploying this code and running the category/token migration.
    console.error("feedback insert (full) failed, trying legacy:", e && e.message);
    try {
      const res = await env.DB.prepare(
        "INSERT INTO feedback (ts, message, email, karyotype, url, ua, country) VALUES (?, ?, ?, ?, ?, ?, ?)"
      ).bind(ts, message.slice(0, 4000), email, karyotype, link, ua, country).run();
      id = res.meta && res.meta.last_row_id; stored = true;
    } catch (e2) { console.error("feedback insert (legacy) failed:", e2 && e2.message); }
  }

  if (env.FEEDBACK_WEBHOOK && message) {
    const text = "New KaryoDraw feedback" + (category ? " [" + category + "]" : "") + "\n" + message.slice(0, 1500) +
      (email ? "\nreply-to: " + email : "") +
      (karyotype ? "\nkaryotype: " + karyotype : "") +
      (link ? "\nview: " + link : "");
    // Chat webhooks vary: Discord expects `content`, Slack expects `text`. Send both.
    ctx.waitUntil(
      fetch(env.FEEDBACK_WEBHOOK, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ content: text, text }),
      }).catch(() => {})
    );
  }

  if (!stored && !env.FEEDBACK_WEBHOOK) {
    return new Response("could not save feedback", { status: 500 });
  }
  // Return the row id + token so the client can enrich this flag with detail.
  return new Response(JSON.stringify({ ok: true, id, token }), {
    status: 200, headers: { "content-type": "application/json" },
  });
}

// GET /api/top — the ranked "Most-studied" list. Cached at the edge for a day so
// D1 is queried at most about once per day per location. Only ever returns the
// karyotype strings in rank order; no counts, no dates, no geo.
async function topResponse(request, env, ctx) {
  const cache = caches.default;
  const cacheKey = new Request(new URL("/api/top", request.url).toString(), { method: "GET" });
  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  let items = [];
  try {
    items = await topKaryotypes(env);
  } catch (e) {
    console.error("top query failed:", e && e.message);
  }
  const res = new Response(JSON.stringify({ items }), {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=86400",
    },
  });
  // Cache even an empty result, so an early-days empty board is not re-queried
  // on every request. It expires within a day and refills as usage accrues.
  ctx.waitUntil(cache.put(cacheKey, res.clone()));
  return res;
}

async function topKaryotypes(env) {
  // Group case- and space-insensitively so "46,XX" and "46, xx" count together;
  // display an actual typed variant (MIN) rather than the normalized key. Rank by
  // distinct days first so broadly-used examples lead. ts is epoch ms; ts/86400000
  // is the UTC day bucket.
  const rs = await env.DB.prepare(
    "SELECT MIN(karyotype) AS k, COUNT(*) AS n, COUNT(DISTINCT ts/86400000) AS days " +
    "FROM usage WHERE type='draw' AND parsed=1 AND karyotype IS NOT NULL " +
    "GROUP BY LOWER(REPLACE(karyotype, ' ', '')) " +
    "HAVING n >= ? AND days >= ? " +
    "ORDER BY days DESC, n DESC, k ASC LIMIT ?"
  ).bind(TOP_MIN_DRAWS, TOP_MIN_DAYS, TOP_LIMIT).all();
  return (rs.results || []).map((r) => r.k).filter(Boolean);
}

async function record(b, country, env) {
  if (!b) return;
  const type = b.type === "pageview" ? "pageview" : "draw";
  // Keep the karyotype capped for storage, but record the full length so we can
  // see whether the cap is ever hit (SELECT count(*) WHERE len > 512).
  const len = type === "draw" && typeof b.k === "string" ? b.k.length : null;
  try {
    await env.DB.prepare(
      "INSERT INTO usage (ts, type, karyotype, parsed, style, bands, show_mode, country, referer, len) " +
      "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
    ).bind(
      Date.now(),
      type,
      type === "draw" ? cap(b.k, 512) : null,
      type === "draw" ? (b.ok ? 1 : 0) : null,
      cap(b.style, 16),
      cap(b.bands, 8),
      cap(b.show, 16),
      country,
      cap(b.ref, 80),
      len
    ).run();
  } catch (e) {
    console.error("usage insert failed:", e && e.message);
  }
}
