// Generated by scripts/build-pages.mjs — normalized ISCN notation -> landing-page slug.
// Used by worker.js to 301-redirect /k/<notation> to its canonical /karyotype/<slug>/.
export const K_TO_SLUG = {
  "46,xx": "normal-female-karyotype",
  "47,xx,+21": "down-syndrome",
  "45,x": "turner-syndrome",
  "47,xxy": "klinefelter-syndrome",
  "46,xy,del(5)(p15.2)": "cri-du-chat-syndrome",
  "46,xx,del(22)(q11.21q11.23)": "digeorge-22q11-deletion",
  "46,xy,inv(9)(p11q13)": "inversion-9",
  "46,x,i(x)(q10)": "isochromosome-xq",
  "46,xy,t(9;22)(q34;q11.2)": "philadelphia-chromosome",
  "45,xx,rob(13;14)(q10;q10)": "robertsonian-translocation-13-14",
  "46,xy,r(13)(p11q34)": "ring-chromosome-13",
  "mos45,x[12]/46,xx[18]": "mosaic-turner-syndrome",
  "46,xy": "normal-male-karyotype",
  "47,xy,+18": "edwards-syndrome",
  "47,xx,+13": "patau-syndrome",
  "47,xxx": "triple-x-syndrome",
  "47,xyy": "xyy-syndrome",
  "46,xx,del(15)(q11.2q13)": "prader-willi-angelman-15q",
  "46,xx,del(4)(p16.3)": "wolf-hirschhorn-syndrome",
  "46,xy,dup(1)(q22q25)": "chromosome-1q-duplication",
  "69,xxy": "triploidy",
  "45,xy,rob(14;21)(q10;q10)": "robertsonian-translocation-14-21",
  "46,xx,del(1)(p36.3)": "chromosome-1p36-deletion",
  "47,xx,+mar": "marker-chromosome"
};
