#!/usr/bin/env python3
"""Build ideogram-data.js from the UCSC hg38 cytoBandIdeo table.

Source: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/cytoBandIdeo.txt.gz
Columns (tab-separated): chrom, chromStart, chromEnd, name (band), gieStain

Output: ../ideogram-data.js defining window.IDEOGRAM = {chromosomes, data}
where each chromosome carries its length, the p/q centromere boundary (bp),
and a compact band list [name, start, end, stain].
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "cytoBandIdeo.hg38.txt")
OUT = os.path.join(HERE, "..", "ideogram-data.js")

ORDER = [str(n) for n in range(1, 23)] + ["X", "Y"]
WANT = {f"chr{c}": c for c in ORDER}

chroms = {c: [] for c in ORDER}
with open(SRC) as fh:
    for line in fh:
        parts = line.rstrip("\n").split("\t")
        if len(parts) != 5:
            continue
        chrom, start, end, name, stain = parts
        if chrom not in WANT:
            continue
        chroms[WANT[chrom]].append((name, int(start), int(end), stain))

for c in ORDER:
    chroms[c].sort(key=lambda b: b[1])


def centromere(bands):
    # p/q boundary = start of the first q-arm band (== end of last p-arm band)
    for name, start, end, stain in bands:
        if name.startswith("q"):
            return start
    return None


lines = []
lines.append("// Chromosome ideogram band data.")
lines.append("// GENERATED by _build_inputs/build_ideogram.py from UCSC hg38 cytoBandIdeo.")
lines.append("// Do not edit by hand. Positions in base pairs (bp). stain = Giemsa band class.")
lines.append("window.IDEOGRAM = {")
lines.append("  chromosomes: [" + ", ".join(f'"{c}"' for c in ORDER) + "],")
lines.append("  data: {")
for c in ORDER:
    bands = chroms[c]
    length = max(b[2] for b in bands)
    cen = centromere(bands)
    lines.append(f'    "{c}": {{')
    lines.append(f"      length: {length}, centromere: {cen},")
    lines.append("      bands: [")
    for name, start, end, stain in bands:
        lines.append(f'        ["{name}", {start}, {end}, "{stain}"],')
    lines.append("      ]")
    lines.append("    },")
lines.append("  }")
lines.append("};")

with open(OUT, "w") as fh:
    fh.write("\n".join(lines) + "\n")

total_bands = sum(len(chroms[c]) for c in ORDER)
print(f"Wrote {OUT}")
print(f"{len(ORDER)} chromosomes, {total_bands} bands total")
for c in ORDER:
    b = chroms[c]
    print(f"  chr{c}: {len(b)} bands, length {max(x[2] for x in b):,} bp, centromere {centromere(b):,} bp")
